/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.3.0 Sat Aug 29 17:11:18 2020.
 */

#include <string.h>
#include <stdio.h>

#include "newacc.h"


static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int xian_acc2_acc_pack(
    uint8_t *dst_p,
    const struct xian_acc2_acc_t *src_p,
    size_t size)
{
    uint16_t acc_x;
    uint16_t acc_y;
    uint16_t acc_z;
    uint16_t t;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    acc_x = (uint16_t)src_p->acc_x;
    dst_p[0] |= pack_right_shift_u16(acc_x, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(acc_x, 0u, 0xffu);
    acc_y = (uint16_t)src_p->acc_y;
    dst_p[2] |= pack_right_shift_u16(acc_y, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(acc_y, 0u, 0xffu);
    acc_z = (uint16_t)src_p->acc_z;
    dst_p[4] |= pack_right_shift_u16(acc_z, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(acc_z, 0u, 0xffu);
    t = (uint16_t)src_p->t;
    dst_p[6] |= pack_right_shift_u16(t, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(t, 0u, 0xffu);

    return (8);
}

int xian_acc2_acc_unpack(
    struct xian_acc2_acc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t acc_x;
    uint16_t acc_y;
    uint16_t acc_z;
    uint16_t t;

    if (size < 8u) {
        return (-EINVAL);
    }

    acc_x = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    acc_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->acc_x = (int16_t)acc_x;
    acc_y = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    acc_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->acc_y = (int16_t)acc_y;
    acc_z = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    acc_z |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->acc_z = (int16_t)acc_z;
    t = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    t |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->t = (int16_t)t;

    return (0);
}

int16_t xian_acc2_acc_acc_x_encode(double value)
{
    return (int16_t)(value / 0.00133333);
}

double xian_acc2_acc_acc_x_decode(int16_t value)
{
    return ((double)value * 0.00133333);
}

bool xian_acc2_acc_acc_x_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t xian_acc2_acc_acc_y_encode(double value)
{
    return (int16_t)(value / 0.00133333);
}

double xian_acc2_acc_acc_y_decode(int16_t value)
{
    return ((double)value * 0.00133333);
}

bool xian_acc2_acc_acc_y_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t xian_acc2_acc_acc_z_encode(double value)
{
    return (int16_t)(value / 0.00133333);
}

double xian_acc2_acc_acc_z_decode(int16_t value)
{
    return ((double)value * 0.00133333);
}

bool xian_acc2_acc_acc_z_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t xian_acc2_acc_t_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double xian_acc2_acc_t_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool xian_acc2_acc_t_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}



int DBC_Decode(VCI_CAN_OBJ* R_message,int R_length,double *matrix, DBC_INFO* dbc_info){
    //printf("I am in~\n\r");
    int matrix_column_value=dbc_info->matrix_column_value;
    int matrix_row=dbc_info->matrix_row;
    int filled_column=dbc_info->filled_column;
    int matrix_row_value=dbc_info->matrix_row_value;
    int timestamp=dbc_info->timestamp;

    int AvaliableSpace=(matrix_row_value-matrix_row-1)*1;
    int T_R_length;
    int ReturnValue;
    if (AvaliableSpace>R_length){
        //printf("Here~\n\r");
        T_R_length=R_length;
        ReturnValue=0;
    }else{
        T_R_length=AvaliableSpace;
        //printf("%d messages was ignored!\n\r",T_R_length-AvaliableSpace);
        ReturnValue=1;
    };
/*DataMap = {  'D_Ac_X_FM': 16,
  'D_Ac_Y_FM': 17,  'M3_A': -1,  'D_Ac_Z_FM': 18,
  'D_Ac_X_RM': 19,  'D_Ac_Y_RM': 20,  'D_Ac_Z_RMXXX': -1,
    'D_Ac_X_Wl_FL': 0,  'D_Ac_Y_Wl_FL': 1,  'D_Ac_Z_Wl_FL': 2,
     'D_Ac_X_Wl_FR': 3,  'D_Ac_Y_Wl_FR': 4,  'D_Ac_Z_Wl_FR': 5,
     'D_Ac_X_Wl_RL': 6,  'D_Ac_Y_Wl_RL': 7,  'D_Ac_Z_Wl_RL': 8,
      'D_Ac_X_Wl_RR': 9,  'D_Ac_Y_Wl_RR': 10,  'D_Ac_Z_Wl_RR': 11,
       'D_Dis_Dmp_FL': 12,  'D_Dis_Dmp_FR': 13,  'D_Dis_Dmp_RL': 14,
       'D_Dis_Dmp_RR': 15,  'D_Ac_Z_RM': 21, }
*/
    for(int i=0;i<T_R_length;i++){
        VCI_CAN_OBJ temp_message=R_message[i];
        //printf("ID %X Data %X hang: %d lie: %d\n\r",temp_message.ID,temp_message.Data,matrix_row,filled_column);

/*        if(temp_message.TimeStamp-timestamp>MAXSTEP){
            //i--;
        }
*/

        timestamp=temp_message.TimeStamp;
        switch (temp_message.ID) {
            case 0x1a1u:
                matrix[matrix_row*matrix_column_value+1]=xian_acc2_acc_acc_x_decode((temp_message.Data[0]<<8)+(temp_message.Data[1]));
                matrix[matrix_row*matrix_column_value+2]=xian_acc2_acc_acc_y_decode((temp_message.Data[2]<<8)+(temp_message.Data[3]));
                matrix[matrix_row*matrix_column_value+3]=xian_acc2_acc_acc_z_decode((temp_message.Data[4]<<8)+(temp_message.Data[5]));
                matrix[matrix_row*matrix_column_value+4]=xian_acc2_acc_t_decode((temp_message.Data[6]<<8)+(temp_message.Data[7]));
                break;

            default:
                return -1;
                break;
        }

        matrix_row++;

/*       filled_column+=4;
        if(filled_column>=matrix_column_value){
            matrix_row++;
            filled_column=0;
        }
*/
    }

    dbc_info->matrix_column_value=matrix_column_value;
    dbc_info->matrix_row=matrix_row;
    dbc_info->filled_column=filled_column;
    dbc_info->matrix_row_value=matrix_row_value;
    dbc_info->timestamp=timestamp;
    return ReturnValue;
}