/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.3.0 Sat Aug 29 17:11:18 2020.
 */

#include <string.h>

#include "cs_mconfig1_500_hz_butterworth200_hz.h"

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_fm;
    uint16_t d_ac_y_fm;
    uint16_t d_ac_z_fm;
    uint16_t m3_a;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_ac_x_fm = (uint16_t)src_p->d_ac_x_fm;
    dst_p[0] |= pack_left_shift_u16(d_ac_x_fm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_ac_x_fm, 8u, 0xffu);
    d_ac_y_fm = (uint16_t)src_p->d_ac_y_fm;
    dst_p[2] |= pack_left_shift_u16(d_ac_y_fm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_ac_y_fm, 8u, 0xffu);
    m3_a = (uint16_t)src_p->m3_a;
    dst_p[4] |= pack_left_shift_u16(m3_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(m3_a, 8u, 0xffu);
    d_ac_z_fm = (uint16_t)src_p->d_ac_z_fm;
    dst_p[6] |= pack_left_shift_u16(d_ac_z_fm, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_ac_z_fm, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_fm;
    uint16_t d_ac_y_fm;
    uint16_t d_ac_z_fm;
    uint16_t m3_a;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_ac_x_fm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_ac_x_fm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_ac_x_fm = (int16_t)d_ac_x_fm;
    d_ac_y_fm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_ac_y_fm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_ac_y_fm = (int16_t)d_ac_y_fm;
    m3_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    m3_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->m3_a = (int16_t)m3_a;
    d_ac_z_fm = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_ac_z_fm |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_ac_z_fm = (int16_t)d_ac_z_fm;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_x_fm_encode(double value)
{
    return (int16_t)(value / -0.00228603067);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_x_fm_decode(int16_t value)
{
    return ((double)value * -0.00228603067);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_x_fm_is_in_range(int16_t value)
{
    return ((value >= 21871) && (value <= -21871));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_y_fm_encode(double value)
{
    return (int16_t)(value / -0.00230328374);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_y_fm_decode(int16_t value)
{
    return ((double)value * -0.00230328374);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_y_fm_is_in_range(int16_t value)
{
    return ((value >= 21708) && (value <= -21708));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_m3_a_encode(double value)
{
    return (int16_t)(value / 0.00061037019);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_m3_a_decode(int16_t value)
{
    return ((double)value * 0.00061037019);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_m3_a_is_in_range(int16_t value)
{
    return ((value >= -32766) && (value <= 32766));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_z_fm_encode(double value)
{
    return (int16_t)(value / 0.00229462477);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_z_fm_decode(int16_t value)
{
    return ((double)value * 0.00229462477);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg0_d_ac_z_fm_is_in_range(int16_t value)
{
    return ((value >= -21790) && (value <= 21790));
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_rm;
    uint16_t d_ac_x_wl_fl;
    uint16_t d_ac_y_rm;
    uint16_t d_ac_z_rmxxx;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_ac_x_rm = (uint16_t)src_p->d_ac_x_rm;
    dst_p[0] |= pack_left_shift_u16(d_ac_x_rm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_ac_x_rm, 8u, 0xffu);
    d_ac_y_rm = (uint16_t)src_p->d_ac_y_rm;
    dst_p[2] |= pack_left_shift_u16(d_ac_y_rm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_ac_y_rm, 8u, 0xffu);
    d_ac_z_rmxxx = (uint16_t)src_p->d_ac_z_rmxxx;
    dst_p[4] |= pack_left_shift_u16(d_ac_z_rmxxx, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d_ac_z_rmxxx, 8u, 0xffu);
    d_ac_x_wl_fl = (uint16_t)src_p->d_ac_x_wl_fl;
    dst_p[6] |= pack_left_shift_u16(d_ac_x_wl_fl, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_ac_x_wl_fl, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_rm;
    uint16_t d_ac_x_wl_fl;
    uint16_t d_ac_y_rm;
    uint16_t d_ac_z_rmxxx;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_ac_x_rm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_ac_x_rm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_ac_x_rm = (int16_t)d_ac_x_rm;
    d_ac_y_rm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_ac_y_rm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_ac_y_rm = (int16_t)d_ac_y_rm;
    d_ac_z_rmxxx = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d_ac_z_rmxxx |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d_ac_z_rmxxx = (int16_t)d_ac_z_rmxxx;
    d_ac_x_wl_fl = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_ac_x_wl_fl |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_ac_x_wl_fl = (int16_t)d_ac_x_wl_fl;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_rm_encode(double value)
{
    return (int16_t)(value / -0.00153051703);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_rm_decode(int16_t value)
{
    return ((double)value * -0.00153051703);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_rm_is_in_range(int16_t value)
{
    return ((value >= 32668) && (value <= -32668));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_y_rm_encode(double value)
{
    return (int16_t)(value / -0.00153359344);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_y_rm_decode(int16_t value)
{
    return ((double)value * -0.00153359344);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_y_rm_is_in_range(int16_t value)
{
    return ((value >= 32603) && (value <= -32603));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_z_rmxxx_encode(double value)
{
    return (int16_t)(value / 0.00152287972);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_z_rmxxx_decode(int16_t value)
{
    return ((double)value * 0.00152287972);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_z_rmxxx_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_wl_fl_encode(double value)
{
    return (int16_t)(value / 0.0061529253);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_wl_fl_decode(int16_t value)
{
    return ((double)value * 0.0061529253);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05429_msg1_d_ac_x_wl_fl_is_in_range(int16_t value)
{
    return ((value >= -32504) && (value <= 32504));
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_fr;
    uint16_t d_ac_y_wl_fl;
    uint16_t d_ac_y_wl_fr;
    uint16_t d_ac_z_wl_fl;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_ac_y_wl_fl = (uint16_t)src_p->d_ac_y_wl_fl;
    dst_p[0] |= pack_left_shift_u16(d_ac_y_wl_fl, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_ac_y_wl_fl, 8u, 0xffu);
    d_ac_z_wl_fl = (uint16_t)src_p->d_ac_z_wl_fl;
    dst_p[2] |= pack_left_shift_u16(d_ac_z_wl_fl, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_ac_z_wl_fl, 8u, 0xffu);
    d_ac_x_wl_fr = (uint16_t)src_p->d_ac_x_wl_fr;
    dst_p[4] |= pack_left_shift_u16(d_ac_x_wl_fr, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d_ac_x_wl_fr, 8u, 0xffu);
    d_ac_y_wl_fr = (uint16_t)src_p->d_ac_y_wl_fr;
    dst_p[6] |= pack_left_shift_u16(d_ac_y_wl_fr, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_ac_y_wl_fr, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_fr;
    uint16_t d_ac_y_wl_fl;
    uint16_t d_ac_y_wl_fr;
    uint16_t d_ac_z_wl_fl;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_ac_y_wl_fl = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_ac_y_wl_fl |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_ac_y_wl_fl = (int16_t)d_ac_y_wl_fl;
    d_ac_z_wl_fl = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_ac_z_wl_fl |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_ac_z_wl_fl = (int16_t)d_ac_z_wl_fl;
    d_ac_x_wl_fr = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d_ac_x_wl_fr |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d_ac_x_wl_fr = (int16_t)d_ac_x_wl_fr;
    d_ac_y_wl_fr = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_ac_y_wl_fr |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_ac_y_wl_fr = (int16_t)d_ac_y_wl_fr;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fl_encode(double value)
{
    return (int16_t)(value / -0.00619665168);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fl_decode(int16_t value)
{
    return ((double)value * -0.00619665168);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fl_is_in_range(int16_t value)
{
    return ((value >= 32275) && (value <= -32275));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_z_wl_fl_encode(double value)
{
    return (int16_t)(value / 0.00604925857);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_z_wl_fl_decode(int16_t value)
{
    return ((double)value * 0.00604925857);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_z_wl_fl_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_x_wl_fr_encode(double value)
{
    return (int16_t)(value / 0.00628082105);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_x_wl_fr_decode(int16_t value)
{
    return ((double)value * 0.00628082105);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_x_wl_fr_is_in_range(int16_t value)
{
    return ((value >= -31842) && (value <= 31842));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fr_encode(double value)
{
    return (int16_t)(value / -0.00612022651);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fr_decode(int16_t value)
{
    return ((double)value * -0.00612022651);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg0_d_ac_y_wl_fr_is_in_range(int16_t value)
{
    return ((value >= 32678) && (value <= -32678));
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_rl;
    uint16_t d_ac_y_wl_rl;
    uint16_t d_ac_z_wl_fr;
    uint16_t d_ac_z_wl_rl;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_ac_z_wl_fr = (uint16_t)src_p->d_ac_z_wl_fr;
    dst_p[0] |= pack_left_shift_u16(d_ac_z_wl_fr, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_ac_z_wl_fr, 8u, 0xffu);
    d_ac_x_wl_rl = (uint16_t)src_p->d_ac_x_wl_rl;
    dst_p[2] |= pack_left_shift_u16(d_ac_x_wl_rl, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_ac_x_wl_rl, 8u, 0xffu);
    d_ac_y_wl_rl = (uint16_t)src_p->d_ac_y_wl_rl;
    dst_p[4] |= pack_left_shift_u16(d_ac_y_wl_rl, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d_ac_y_wl_rl, 8u, 0xffu);
    d_ac_z_wl_rl = (uint16_t)src_p->d_ac_z_wl_rl;
    dst_p[6] |= pack_left_shift_u16(d_ac_z_wl_rl, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_ac_z_wl_rl, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_rl;
    uint16_t d_ac_y_wl_rl;
    uint16_t d_ac_z_wl_fr;
    uint16_t d_ac_z_wl_rl;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_ac_z_wl_fr = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_ac_z_wl_fr |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_ac_z_wl_fr = (int16_t)d_ac_z_wl_fr;
    d_ac_x_wl_rl = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_ac_x_wl_rl |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_ac_x_wl_rl = (int16_t)d_ac_x_wl_rl;
    d_ac_y_wl_rl = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d_ac_y_wl_rl |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d_ac_y_wl_rl = (int16_t)d_ac_y_wl_rl;
    d_ac_z_wl_rl = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_ac_z_wl_rl |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_ac_z_wl_rl = (int16_t)d_ac_z_wl_rl;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_fr_encode(double value)
{
    return (int16_t)(value / 0.00625763984);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_fr_decode(int16_t value)
{
    return ((double)value * 0.00625763984);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_fr_is_in_range(int16_t value)
{
    return ((value >= -31960) && (value <= 31960));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_x_wl_rl_encode(double value)
{
    return (int16_t)(value / 0.0092200935);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_x_wl_rl_decode(int16_t value)
{
    return ((double)value * 0.0092200935);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_x_wl_rl_is_in_range(int16_t value)
{
    return ((value >= -21691) && (value <= 21691));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_y_wl_rl_encode(double value)
{
    return (int16_t)(value / -0.0091784991);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_y_wl_rl_decode(int16_t value)
{
    return ((double)value * -0.0091784991);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_y_wl_rl_is_in_range(int16_t value)
{
    return ((value >= 21790) && (value <= -21790));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_rl_encode(double value)
{
    return (int16_t)(value / -0.0092200935);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_rl_decode(int16_t value)
{
    return ((double)value * -0.0092200935);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05431_msg1_d_ac_z_wl_rl_is_in_range(int16_t value)
{
    return ((value >= 21691) && (value <= -21691));
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_rr;
    uint16_t d_ac_y_wl_rr;
    uint16_t d_ac_z_wl_rr;
    uint16_t d_dis_dmp_fl;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_ac_x_wl_rr = (uint16_t)src_p->d_ac_x_wl_rr;
    dst_p[0] |= pack_left_shift_u16(d_ac_x_wl_rr, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_ac_x_wl_rr, 8u, 0xffu);
    d_ac_y_wl_rr = (uint16_t)src_p->d_ac_y_wl_rr;
    dst_p[2] |= pack_left_shift_u16(d_ac_y_wl_rr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_ac_y_wl_rr, 8u, 0xffu);
    d_ac_z_wl_rr = (uint16_t)src_p->d_ac_z_wl_rr;
    dst_p[4] |= pack_left_shift_u16(d_ac_z_wl_rr, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d_ac_z_wl_rr, 8u, 0xffu);
    d_dis_dmp_fl = (uint16_t)src_p->d_dis_dmp_fl;
    dst_p[6] |= pack_left_shift_u16(d_dis_dmp_fl, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_dis_dmp_fl, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_x_wl_rr;
    uint16_t d_ac_y_wl_rr;
    uint16_t d_ac_z_wl_rr;
    uint16_t d_dis_dmp_fl;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_ac_x_wl_rr = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_ac_x_wl_rr |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_ac_x_wl_rr = (int16_t)d_ac_x_wl_rr;
    d_ac_y_wl_rr = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_ac_y_wl_rr |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_ac_y_wl_rr = (int16_t)d_ac_y_wl_rr;
    d_ac_z_wl_rr = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d_ac_z_wl_rr |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d_ac_z_wl_rr = (int16_t)d_ac_z_wl_rr;
    d_dis_dmp_fl = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_dis_dmp_fl |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_dis_dmp_fl = (int16_t)d_dis_dmp_fl;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_x_wl_rr_encode(double value)
{
    return (int16_t)(value / 0.00916471757);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_x_wl_rr_decode(int16_t value)
{
    return ((double)value * 0.00916471757);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_x_wl_rr_is_in_range(int16_t value)
{
    return ((value >= -21822) && (value <= 21822));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_y_wl_rr_encode(double value)
{
    return (int16_t)(value / 0.00924803318);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_y_wl_rr_decode(int16_t value)
{
    return ((double)value * 0.00924803318);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_y_wl_rr_is_in_range(int16_t value)
{
    return ((value >= -21626) && (value <= 21626));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_z_wl_rr_encode(double value)
{
    return (int16_t)(value / 0.00919232214);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_z_wl_rr_decode(int16_t value)
{
    return ((double)value * 0.00919232214);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_ac_z_wl_rr_is_in_range(int16_t value)
{
    return ((value >= -21757) && (value <= 21757));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_dis_dmp_fl_encode(double value)
{
    return (int16_t)(value / 0.0366222114);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_dis_dmp_fl_decode(int16_t value)
{
    return ((double)value * 0.0366222114);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg0_d_dis_dmp_fl_is_in_range(int16_t value)
{
    return ((value >= -16383) && (value <= 16383));
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_pack(
    uint8_t *dst_p,
    const struct cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_t *src_p,
    size_t size)
{
    uint16_t d_ac_z_rm;
    uint16_t d_dis_dmp_fr;
    uint16_t d_dis_dmp_rl;
    uint16_t d_dis_dmp_rr;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    d_dis_dmp_fr = (uint16_t)src_p->d_dis_dmp_fr;
    dst_p[0] |= pack_left_shift_u16(d_dis_dmp_fr, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(d_dis_dmp_fr, 8u, 0xffu);
    d_dis_dmp_rl = (uint16_t)src_p->d_dis_dmp_rl;
    dst_p[2] |= pack_left_shift_u16(d_dis_dmp_rl, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(d_dis_dmp_rl, 8u, 0xffu);
    d_dis_dmp_rr = (uint16_t)src_p->d_dis_dmp_rr;
    dst_p[4] |= pack_left_shift_u16(d_dis_dmp_rr, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(d_dis_dmp_rr, 8u, 0xffu);
    d_ac_z_rm = (uint16_t)src_p->d_ac_z_rm;
    dst_p[6] |= pack_left_shift_u16(d_ac_z_rm, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(d_ac_z_rm, 8u, 0xffu);

    return (8);
}

int cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_unpack(
    struct cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t d_ac_z_rm;
    uint16_t d_dis_dmp_fr;
    uint16_t d_dis_dmp_rl;
    uint16_t d_dis_dmp_rr;

    if (size < 8u) {
        return (-EINVAL);
    }

    d_dis_dmp_fr = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    d_dis_dmp_fr |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->d_dis_dmp_fr = (int16_t)d_dis_dmp_fr;
    d_dis_dmp_rl = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    d_dis_dmp_rl |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->d_dis_dmp_rl = (int16_t)d_dis_dmp_rl;
    d_dis_dmp_rr = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    d_dis_dmp_rr |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->d_dis_dmp_rr = (int16_t)d_dis_dmp_rr;
    d_ac_z_rm = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    d_ac_z_rm |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->d_ac_z_rm = (int16_t)d_ac_z_rm;

    return (0);
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_fr_encode(double value)
{
    return (int16_t)(value / 0.0366222114);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_fr_decode(int16_t value)
{
    return ((double)value * 0.0366222114);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_fr_is_in_range(int16_t value)
{
    return ((value >= -16383) && (value <= 16383));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rl_encode(double value)
{
    return (int16_t)(value / 0.0732444228);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rl_decode(int16_t value)
{
    return ((double)value * 0.0732444228);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rl_is_in_range(int16_t value)
{
    return ((value >= -8191) && (value <= 8191));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rr_encode(double value)
{
    return (int16_t)(value / 0.0366222114);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rr_decode(int16_t value)
{
    return ((double)value * 0.0366222114);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_dis_dmp_rr_is_in_range(int16_t value)
{
    return ((value >= -16383) && (value <= 16383));
}

int16_t cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_ac_z_rm_encode(double value)
{
    return (int16_t)(value / 0.00152287972);
}

double cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_ac_z_rm_decode(int16_t value)
{
    return ((double)value * 0.00152287972);
}

bool cs_mconfig1_500_hz_butterworth200_hz_admm_05432_msg1_d_ac_z_rm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
